// Portfolio data: single source of truth
window.PORTFOLIO = {
  name: "Hanith Tummalapalli",
  alias: "hanith",
  title: "Data Analyst → Data Engineer",
  location: "Peoria, IL · USA",
  timezone: "CST / UTC-6",
  availability: "Summer 2026",
  email: "thanith1362@gmail.com",
  phone: "+1 (309) 323-1406",
  github: "https://github.com/hanith1362",
  linkedin: "https://www.linkedin.com/in/hanithtummalapalli/",
  gpa: "4.0",
  school: "Bradley University, IL · M.S. Data Science",
  schoolDates: "Jan 2025 → Dec 2026",

  headline: {
    line1: "I turn messy data",
    line2: "into decisions",
    line3: "people act on.",
  },

  intro:
    "Data engineer & analyst building pipelines, dashboards, and AI tools that ship. Microsoft-certified Power BI Data Analyst with 3+ yrs across enterprise ETL, cloud warehousing, and ML research — currently finishing an M.S. in Data Science (GPA 4.0) at Bradley University.",

  heroStats: [
    { num: "40", unit: "%", cap: "ETL reliability lift · SSIS" },
    { num: "70", unit: "%", cap: "faster query turnaround · DataMate" },
    { num: "30", unit: "%", cap: "dashboard perf gain · Power BI" },
    { num: "230", unit: "K", cap: "records · ML heart-disease model" },
  ],

  keywords: [
    "Data Engineering","ETL","Azure Data Factory","SSIS","DBT","Snowflake",
    "Power BI","SQL","Python","Airflow","Spark","ML / NLP","Dimensional Modeling",
    "Microsoft Fabric","Synapse","Star Schema","DAX","Governance","Dashboarding"
  ],

  skills: [
    {
      n: "01",
      t: "Data Engineering / ETL",
      items: [
        { k: "SSIS", pri: true },
        { k: "Azure Data Factory", pri: true },
        { k: "DBT", pri: true },
        { k: "Airflow" },
        { k: "Spark" },
        { k: "Alteryx" },
        { k: "Microsoft Fabric" },
        { k: "Synapse" },
      ],
    },
    {
      n: "02",
      t: "Languages & Modeling",
      items: [
        { k: "SQL", pri: true },
        { k: "Python", pri: true },
        { k: "R" },
        { k: "DAX", pri: true },
        { k: "CTEs · Window fns" },
        { k: "Dimensional Modeling" },
        { k: "Statistical Analysis" },
      ],
    },
    {
      n: "03",
      t: "Warehouses & DBs",
      items: [
        { k: "Snowflake", pri: true },
        { k: "SQL Server" },
        { k: "PostgreSQL" },
        { k: "BigQuery" },
        { k: "MySQL" },
        { k: "Azure Synapse" },
        { k: "NoSQL" },
      ],
    },
    {
      n: "04",
      t: "BI & Visualization",
      items: [
        { k: "Power BI", pri: true },
        { k: "Tableau" },
        { k: "Superset" },
        { k: "Qlik" },
        { k: "Advanced Excel" },
        { k: "Power Query" },
      ],
    },
    {
      n: "05",
      t: "Cloud & Platforms",
      items: [
        { k: "Azure", pri: true },
        { k: "AWS" },
        { k: "GCP" },
        { k: "Docker" },
        { k: "Kubernetes" },
        { k: "Git" },
      ],
    },
    {
      n: "06",
      t: "AI & Analytics",
      items: [
        { k: "NLP", pri: true },
        { k: "Machine Learning", pri: true },
        { k: "Feature Engineering" },
        { k: "AUC / PR metrics" },
        { k: "LLM → SQL" },
      ],
    },
  ],

  projects: [
    {
      id: "resq360",
      idx: "01",
      name: "RESQ360",
      tagline: "AI ambulance dispatch & real-time tracking",
      kind: "Distributed System · FastAPI · WebSockets",
      year: "2025",
      status: "Production",
      award: "🚑 Flagship System",
      impact: "Real-time · <200ms dispatch",
      tags: ["FastAPI", "WebSockets", "ML", "Docker"],
      stack: ["FastAPI", "PostgreSQL", "WebSockets", "Docker", "Python", "scikit-learn"],
      problem: "Emergency dispatch is still phone-and-paper in most regions — no live GPS, no ETA to hospitals, and no triage intelligence. Seconds cost lives.",
      solution: "Engineered a real-time dispatch platform: FastAPI backend ingests GPS telemetry, WebSockets broadcast ambulance positions to control rooms and hospitals, and an ML severity classifier routes cases to the right trauma center with ETA. Time-series data persists in PostgreSQL; the full stack is containerized with Docker for single-command deploy.",
      impactPts: [
        "Sub-200ms end-to-end dispatch latency under load",
        "Handled 500+ concurrent GPS streams in load tests",
        "ML severity classifier reaches 87% top-1 accuracy",
        "Event-driven hospital alerts with live ETA updates",
      ],
      learned: [
        "FastAPI + async WebSockets scales far past Flask for telemetry fan-out",
        "Time-series partitioning in Postgres keeps GPS tables queryable at millions of rows",
        "Dockerize early — reproducibility beats 'works on my laptop' debugging",
        "Severity models need calibrated confidence, not just a class label",
      ],
      viz: "resq",
      links: { github: "https://github.com/hanith1362" },
    },
    {
      id: "datamate",
      idx: "02",
      name: "DataMate",
      tagline: "Natural-language → SQL engine",
      kind: "AI Tool · Python · Django",
      year: "2024",
      status: "Hackathon Winner",
      award: "🏆 Hackathon Winner",
      impact: "−70% query turnaround",
      tags: ["AI", "NL→SQL", "Hackathon"],
      stack: ["Python", "Django", "SQL", "LLM", "PostgreSQL"],
      problem: "Business teams waited days for analysts to write ad-hoc SQL, blocking decisions and burning analyst hours on repetitive joins.",
      solution: "Architected an LLM-powered query engine with a Django backend, multi-database routing, and schema-aware grounding so generated SQL actually runs in production.",
      impactPts: [
        "Cut query turnaround by ~70% in user testing",
        "Reduced hallucinated columns by 90% via DDL injection",
        "P50 latency 1.3s after caching schema embeddings",
      ],
      learned: [
        "Schema grounding beats raw prompting",
        "Execution sandbox + read-only roles are non-negotiable for LLM-generated SQL",
        "Transparency builds trust: show the SQL, don't hide the model",
      ],
      viz: "datamate",
      links: { github: "https://github.com/hanith1362" },
    },
    {
      id: "stocks",
      idx: "03",
      name: "Stock Exchange Simulator",
      tagline: "Real-time trading · WebSockets · AI picks",
      kind: "Full-stack · Django + React",
      year: "2024",
      status: "Shipped",
      impact: "<100ms order book",
      tags: ["Full-stack", "WebSockets", "AI"],
      stack: ["Django", "React", "WebSockets", "PostgreSQL", "Redis"],
      problem: "Students learning markets had no safe sandbox to practice real order flow — paper-trading apps only showed PnL screenshots.",
      solution: "Built a full-stack simulator: Django Channels backend streams ticks over WebSockets to a React client, with portfolio tracking, a competitive leaderboard, and AI-driven buy/sell recommendations.",
      impactPts: [
        "Sub-100ms order book updates over WebSockets",
        "Portfolio + leaderboard for competitive learning",
        "AI recommendations based on momentum + sentiment signals",
      ],
      learned: [
        "Channels groups + Redis pub-sub beat polling for fan-out",
        "State machines > flags for order lifecycle",
        "AI recs need a confidence score or users over-trust them",
      ],
      viz: "stocks",
      links: { github: "https://github.com/hanith1362" },
    },
    {
      id: "fda",
      idx: "04",
      name: "FDA Drug Data Pipeline",
      tagline: "1.6M JSON records → normalized MySQL",
      kind: "ETL · Data Engineering",
      year: "2024",
      status: "Production",
      impact: "1.6M records · 3NF schema",
      tags: ["ETL", "MySQL", "Data Quality"],
      stack: ["Python", "MySQL", "pandas", "JSON parsing"],
      problem: "Raw FDA drug data ships as nested, inconsistent JSON with ~1.6M records — unusable for analytics without heavy cleaning and a real schema.",
      solution: "Designed a Python pipeline that stream-parses the JSON, normalizes nested fields, and lands it in a 3NF MySQL schema with proper PK/FK relationships and query-optimized indexing.",
      impactPts: [
        "Processed 1.6M drug records end-to-end",
        "Designed a 3NF schema with 8 related tables",
        "Reduced duplicate records by 23% via dedup logic",
      ],
      learned: [
        "Stream-parse nested JSON; loading it all into memory will OOM",
        "Validate at the boundary, not mid-pipeline",
        "Indexing strategy should follow query patterns, not gut feel",
      ],
      viz: "fda",
      links: { github: "https://github.com/hanith1362" },
    },
    {
      id: "healthcare",
      idx: "05",
      name: "Healthcare Data Pipeline",
      tagline: "On-prem SQL → Azure Synapse, clinical-grade",
      kind: "ETL · Azure · Healthcare",
      year: "2024",
      status: "Production",
      impact: "HIPAA-aligned · 12 daily loads",
      tags: ["ADF", "Synapse", "Governance"],
      stack: ["Azure Data Factory", "Synapse", "SQL Server", "Power BI"],
      problem: "Clinical teams were stuck in Excel exports across facilities — no cross-site reporting, no governance, no freshness SLAs.",
      solution: "Built ADF pipelines that lift patient + clinical data from on-prem SQL Server into Azure Synapse with PHI masking, lineage tags, and quality gates. Power BI dashboards serve clinicians directly.",
      impactPts: [
        "12 production loads/day with incremental CDC",
        "6× faster loads after switching from full reloads",
        "Single governance plane across 4 data domains",
      ],
      learned: [
        "Governance isn't a step — it's a column in every table",
        "Incremental CDC > full reloads past 10GB",
        "Freshness SLAs matter more to owners than schemas",
      ],
      viz: "pipeline",
    },
    {
      id: "finwh",
      idx: "06",
      name: "Financial Data Warehouse",
      tagline: "Star-schema DBT models on Snowflake",
      kind: "Warehousing · DBT · Snowflake",
      year: "2024",
      status: "Production",
      impact: "Star schema · 40+ DAX measures",
      tags: ["DBT", "Snowflake", "Star Schema"],
      stack: ["DBT", "Snowflake", "SQL", "Power BI", "DAX"],
      problem: "Finance had no single source of truth for month-end: every team ran its own SQL, numbers never matched, reconciliation took days.",
      solution: "Modeled DBT transforms from raw feeds into conformed fact + dimension tables on Snowflake. Power BI serves drill-through dashboards with 40+ DAX measures for planning, variance, and trend.",
      impactPts: [
        "One source of truth across 3 entities + 2 currencies",
        "DBT tests catch bad data before it reaches reports",
        "Incremental materialization cut warehouse cost ~35%",
      ],
      learned: [
        "DBT tests > Slack apologies",
        "Semantic layer belongs at the warehouse, not in BI",
        "Type 2 SCDs solve late-arriving dimensions cleanly",
      ],
      viz: "star",
    },
  ],

  experience: [
    {
      role: "Graduate Assistant",
      co: "Bradley University",
      loc: "Peoria, IL · On-site",
      start: "Jan 2026",
      end: "Present",
      active: true,
      bullets: [
        "Supporting graduate research in <b>data analytics</b> and ML coursework — built reusable Python notebooks and SQL templates used across the program.",
        "Maintain research datasets, automate cleaning + validation scripts, and triage technical issues for faculty and students.",
        "Partner with faculty on data-heavy assignments, grading infra, and TA duties for core analytics courses.",
      ],
      metrics: [
        { lb: "Program", vl: "MSDS · Bradley" },
        { lb: "Focus", vl: "Research + TA" },
        { lb: "Stack", vl: "Python · SQL" },
      ],
    },
    {
      role: "Analytics Engineer",
      co: "MedLaunch Concepts LLC",
      loc: "USA · Healthcare Tech",
      start: "Jan 2026",
      end: "Mar 2026",
      active: false,
      bullets: [
        "Engineered <b>Python ETL pipelines</b> integrating <b>Oracle DB</b>, <b>Salesforce CRM</b>, and compliance documents into a unified <b>MongoDB</b> store.",
        "Eliminated manual consolidation across <b>3 source systems</b>, cutting weekly analyst effort to near-zero.",
        "Automated ingestion of <b>500+ monthly compliance documents</b> with schema validation and PHI masking (<b>HIPAA</b>-compliant).",
        "Designed idempotent load patterns and reconciliation checks to guarantee data fidelity across runs.",
      ],
      metrics: [
        { lb: "Systems unified", vl: "3 → 1" },
        { lb: "Docs / month", vl: "500+" },
        { lb: "Compliance", vl: "HIPAA" },
      ],
    },
    {
      role: "Research Assistant · Machine Learning",
      co: "Bradley University",
      loc: "Peoria, IL",
      start: "Aug 2025",
      end: "Dec 2025",
      active: false,
      bullets: [
        "Trained ML models to predict heart disease on <b>230K patient records</b>. Improved accuracy by <b>+8%</b>.",
        "Applied preprocessing, feature engineering, and statistical modeling to optimize <b>AUC</b> and <b>precision-recall</b>.",
        "Benchmarked multiple algorithms and shipped the top performer with reproducible training + evaluation scripts.",
      ],
      metrics: [
        { lb: "Dataset", vl: "230K rows" },
        { lb: "Accuracy Δ", vl: "+8%" },
        { lb: "Stack", vl: "Python · sklearn" },
      ],
    },
    {
      role: "Data Analyst",
      co: "Praval Infotech · Client: Digital Realty",
      loc: "Hyderabad, India",
      start: "Jan 2024",
      end: "Jan 2025",
      active: false,
      bullets: [
        "Built & maintained <b>SSIS</b> packages for automated DB loading — cut job failures by <b>−40%</b>.",
        "Integrated <b>Power BI</b> with SSMS + <b>Microsoft Fabric</b> to deliver scalable operational and exec reporting.",
        "Optimized <b>SQL</b> queries across warehouse marts — dashboard load + refresh times up by <b>+30%</b>.",
        "Drove the requirements-to-KPI loop with stakeholders for supply-chain and ops analytics.",
      ],
      metrics: [
        { lb: "ETL reliability", vl: "+40%" },
        { lb: "Dashboard perf", vl: "+30%" },
        { lb: "Domain", vl: "Data Center Ops" },
      ],
    },
    {
      role: "Data Analyst",
      co: "Vertocity",
      loc: "Hyderabad, India",
      start: "Jul 2022",
      end: "Oct 2023",
      active: false,
      bullets: [
        "Built a <b>Django</b>-based ERP to centralize progress tracking and staff activity.",
        "Shipped Excel dashboards with <b>Power Query</b> + <b>Power Pivot</b> — reporting time <b>−30%</b>.",
        "Led data-informed student performance analysis across cohorts.",
      ],
      metrics: [
        { lb: "Reporting time", vl: "−30%" },
        { lb: "Built", vl: "Django ERP" },
        { lb: "Tooling", vl: "Power Query" },
      ],
    },
  ],

  certs: [
    {
      ic: "PL",
      name: "Microsoft Certified: Power BI Data Analyst Associate",
      iss: "Microsoft",
      code: "PL-300",
      status: "Active",
      date: "2024",
      url: "https://learn.microsoft.com/en-us/users/hanithtummalapalli-2732/credentials/d9985a616b773ead",
    },
    {
      ic: "SF",
      name: "SnowPro Core Certification",
      iss: "Snowflake",
      code: "SnowPro",
      status: "Active",
      date: "2025",
      url: "https://achieve.snowflake.com/f97f955b-7a56-4c28-a3b8-2d2bb6592fd9#acc.RkCVSM8A",
    },
    {
      ic: "MS",
      name: "M.S. Data Science · GPA 4.0",
      iss: "Bradley University",
      code: "In progress",
      status: "Current",
      date: "2025 → 2026",
      url: "",
    },
    {
      ic: "RA",
      name: "Research Assistant · ML in Healthcare",
      iss: "Bradley University",
      code: "Active",
      status: "Current",
      date: "2025 →",
      url: "",
    },
  ],
};
